name: Test

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.12"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
          cache: poetry

      - name: Install project
        run: poetry install --with=dev --with=ci --no-interaction

      - name: Add problem matchers
        run: echo "::add-matcher::.github/problem-matchers/mypy.json"

      - name: Lint
        run: poetry run ruff check --output-format=github .
        if: always()

      - name: Unit test
        run: poetry run pytest --verbose
        if: always()

      - name: Type check
        run: poetry run mypy celebi
        if: always()
